Improve unity support
KuraiAndras/Serilog.Sinks.Unity3D pull request #6
Opened 2022-11-15 15:53 UTC by GwendalBroudin-Emoko

* Add support for unity context object (use UnitySinkExtensions.WithUnityContext)
* Use UnityEngine.ILogger instead of Debug.log for better flexibility

_I know the dictionary implementation is not that great, but I didn't find another way to pass raw object to the sink for now_

2022-11-22 23:28 UTC, KuraiAndras commented
So, a couple of things here:
1. I am not really seeing the usecase here. How is this feature supposed to be used? I (and I suppose most people) set up the logger once, around the start of your application and then don't create a new logger. With this are you supposed to set up a new instance of the logger for every `MonoBehaviour`?
2. Using switch expressions does not work with older Unity versions. Right now the package supports Unity version from 2019 and up, and right now I don't see the need to change that.
3. What does the Unity `ILogger` provide flexibility? If I understand it correctly, it should be a nice logging abstraction, and you can create you own implementation for it. Why would a Serilog library need this? If you want to log to multiple places other than the Unity debug log, then just use other Serilog sinks like the File sink, or create your own implementation.

Other than that, having the ability to pass a context object to the Unity logging mechanism, is something that would be nice.

2022-11-22 23:29 UTC, KuraiAndras requested changes

2022-11-22 23:29 UTC, KuraiAndras commented on Serilog.Sinks.Unity3D/Assets/Serilog.Sinks.Unity3D/Unity3DLogEventSink.cs
> +                };
Not compatible with Unity 2019

2022-11-23 09:17 UTC, GwendalBroudin-Emoko commented
The use of ILogger instead of Debug.Log... is just for custom implementation of [Unity Logger](https://docs.unity3d.com/ScriptReference/ILogger.html) and Debug.Log actually use Unity's default implementation Debug.unityLogger.

I recall that some custom logging UI for Unity use this with [ILogHandler](https://docs.unity3d.com/ScriptReference/ILogHandler.html), this change facilitates the integration of those packages.

2022-12-01 08:50 UTC, GwendalBroudin-Emoko commented
Hi @KuraiAndras, could you review the change I made?

2022-12-01 09:39 UTC, KuraiAndras commented
Sorry, I will try to take a look later today

2022-12-06 18:43 UTC, KuraiAndras commented on Serilog.Sinks.Unity3D/Assets/Serilog.Sinks.Unity3D/UnitySinkExtensions.cs
> +            Unity3DLogEventSink._objectstoLog.TryAdd(id, context);
With Unity 2019.2.0 the Dictionary<T,R> type does not have the TryAdd method, and this does not compile in the editor
![image](https://user-images.githubusercontent.com/19240945/205995342-8b8bb80b-5ee9-4951-921d-d69d4d1feffc.png)

2022-12-06 18:48 UTC, KuraiAndras commented
So, how would you intend to use the `WithUnityContext` method? Every user script creates their own instance of the `ILogger`? Also, not really a fan of using a static dictionary to store `UnityObject`s

2022-12-06 19:05 UTC, KuraiAndras commented on Serilog.Sinks.Unity3D/Assets/Serilog.Sinks.Unity3D/UnitySinkExtensions.cs
> +            UnityEngine.ILogger logger = null)
If we add an ILogger parameter to this method, then why not support ILogger on the other method too?

2022-12-06 19:05 UTC, KuraiAndras commented on Serilog.Sinks.Unity3D/Assets/Serilog.Sinks.Unity3D/UnitySinkExtensions.cs
> +        public static ILogger WithUnityContext(this ILogger logger, UnityEngine.Object context)
This method should have comments in a similar fashing as on the other overloads

2022-12-06 19:08 UTC, KuraiAndras requested changes
I am not comfortable with the usage of the static dictionary for logging the context objects, also the whole thing does not compile (even after fixing the switch expressions), so you probably did not open this with the intended Unity version.

Also, Please provide sample usage of how would providing an object context look like with multiple scripts

2022-12-06 19:09 UTC, KuraiAndras commented
Even though the PR cannot be compiled in Unity 2019, I have started working on updating the package to Unity 2021.3, as the newer versions of the visual studio integration do not support the 2019 version.

2022-12-06 19:36 UTC, KuraiAndras commented
Even though the PR cannot be compiled in Unity 2019, I have started working on updating the package to Unity 2021.3, as the newer versions of the visual studio integration do not support the 2019 version.

2022-12-06 22:17 UTC, KuraiAndras commented
This feature (with others) is included in the 3.0.0 version. Thank you for bringing this to my attention and for providing the initial implementation!

2022-12-06 22:17 UTC, closed without merging